# Generated by Django 2.0.10 on 2019-01-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(max_length=200)),
                ('numero_serie', models.CharField(max_length=200)),
                ('avaria', models.TextField()),
                ('aguarda_encomenda', models.BooleanField(default=False)),
                ('preco', models.FloatField(blank=True, default=None, null=True)),
                ('estado', models.CharField(max_length=200)),
                ('arranjo', models.TextField()),
            ],
        ),
    ]
