# Generated by Django 2.0.10 on 2019-01-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reparacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('fornecedor', models.CharField(max_length=200)),
                ('nome_peca', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('preco', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reparacao',
            name='arranjo',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
