# Generated by Django 2.0.10 on 2019-01-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reparacoes', '0002_auto_20190112_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_peca', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField(default=0)),
            ],
        ),
    ]
