# Generated by Django 2.0.10 on 2019-01-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reparacoes', '0004_auto_20190113_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='nome_peca',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantidade',
            field=models.IntegerField(default=None),
        ),
    ]
