# Generated by Django 2.0.10 on 2019-01-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reparacoes', '0006_auto_20190113_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
