# Generated by Django 2.0.10 on 2019-01-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reparacoes', '0007_auto_20190113_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacao',
            name='estado',
            field=models.CharField(choices=[('ANL', 'Por Analisar'), ('AGENC', 'Aguardar Encomenda'), ('ARR', 'Arranjado')], max_length=20),
        ),
    ]
