# Generated by Django 2.0.10 on 2019-01-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reparacoes', '0010_auto_20190113_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='localidade',
            field=models.CharField(max_length=30),
        ),
    ]
