# Generated by Django 2.0.10 on 2019-01-13 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reparacoes', '0011_auto_20190113_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='nome_peca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reparacoes.Peca'),
        ),
    ]
