# Generated by Django 2.0.10 on 2019-01-13 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Reparacoes', '0012_auto_20190113_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
