# Generated by Django 2.0.10 on 2019-01-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reparacoes', '0013_encomenda_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
