# Generated by Django 2.0.10 on 2019-01-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reparacoes', '0014_auto_20190113_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacao',
            name='estado',
            field=models.CharField(choices=[('Em Analise', 'Em Analise'), ('Arranjado', 'Arranjado')], max_length=20),
        ),
    ]
